-- MySQL Script generated by MySQL Workbench
-- Tue Nov 17 15:24:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema user_authentication
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user_authentication
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user_authentication` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `user_authentication` ;

-- -----------------------------------------------------
-- Table `user_authentication`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_authentication`.`admin` (
  `Username` VARCHAR(45) NOT NULL,
  `DateSubmitted` VARCHAR(45) NULL DEFAULT NULL,
  `ResetApproval` TINYINT NULL DEFAULT '0',
  `Display` VARCHAR(45) NULL DEFAULT '0',
  PRIMARY KEY (`Username`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_authentication`.`bannedpasswords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_authentication`.`bannedpasswords` (
  `ItemNo` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ItemNo`),
  UNIQUE INDEX `ItemNo_UNIQUE` (`ItemNo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_authentication`.`securityquestions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_authentication`.`securityquestions` (
  `QuestionNo` INT NOT NULL AUTO_INCREMENT,
  `Question` VARCHAR(75) NULL DEFAULT NULL,
  PRIMARY KEY (`QuestionNo`),
  UNIQUE INDEX `QuestionNo_UNIQUE` (`QuestionNo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `user_authentication`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_authentication`.`user` (
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `FullName` VARCHAR(45) NOT NULL,
  `DateOfBirth` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `SSN` INT NOT NULL,
  `Question1` VARCHAR(75) NOT NULL,
  `Answer1` VARCHAR(100) NOT NULL,
  `Question2` VARCHAR(75) NOT NULL,
  `Answer2` VARCHAR(100) NOT NULL,
  `Question3` VARCHAR(75) NOT NULL,
  `Answer3` VARCHAR(100) NOT NULL,
  `admin_Username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Username`, `admin_Username`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  INDEX `fk_user_admin_idx` (`admin_Username` ASC) INVISIBLE,
  CONSTRAINT `fk_user_admin`
    FOREIGN KEY (`admin_Username`)
    REFERENCES `user_authentication`.`admin` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
